apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  replicas: 2
  selector:
      matchLabels:
        app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: prakashsharma91/account-service
        ports:
        - containerPort: 8080